NDefines.NCountry.MAXIMUM_CONDOTTIERI = 15                   -- Base number of units you can rent out
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4 
NDefines.NCountry.POLICY_COST = 0                     -- Monthly cost per policy
NDefines.NCountry.PS_REDUCE_INFLATION = 75
NDefines.NCountry.PS_MOVE_TRADE_PORT = 100 
NDefines.NCountry.PS_CHANGE_CULTURE = 8 
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 75 
NDefines.NCountry.CORE_HAD_CLAIM = 0.15             -- Impacts MODIFIER_CORE_CREATION
NDefines.NCountry.CORE_HAD_PERMANENT_CLAIM = 0.30            -- Impacts MODIFIER_CORE_CREATION
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.20                -- The part of the idea group spent that will be refunded upon abandonment. 
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 8              -- How many months it will take to change culture in a province, per development.
NDefines.NCountry.PS_SCORCH_EARTH = 15
NDefines.NCountry.CORRUPTION_FROM_BANNERS = 4
NDefines.NCountry.CAN_CONVERT_TERRITORY_RELIGION = 1
NDefines.NCountry.PS_BOOST_MILITARIZATION = 35
NDefines.NEconomy.INFLATION_FROM_LOAN = 0.15                       -- increase per loan
NDefines.NEconomy.BANKRUPTCY_DURATION = 8 
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 8	-- Bankruptcy will destroy building that have been build in the latest X amount of years. Set to zero to disable the destruction mechanic.
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 20
NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0.75
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.5
NDefines.NMilitary.SAILOR_MAINTAINANCE = 0.015
NDefines.NMilitary.MERCENARY_SUPPORT_LIMIT_FRACTION = 0.20
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 20
NDefines.NMilitary.DELIBERATE_RETREAT_MORALE_PENALTY = 0.1
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.6
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 7.5				-- Cost to create janissaries (per unit)
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0
NDefines.NReligion.PIETY_ACTION_COOLDOWN = 10
NDefines.NReligion.ORTHODOX_ICON_DURATION_MONTHS = 120
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 5475
NDefines.NReligion.CHURCH_POWER_RATE_SCALE = 0.05 
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.02
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 40
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 60	
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.075
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = -0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.44
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.30
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 20
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200